### ISSUE TITLE
Reset/normalize

### ISSUE THREAD

**Issue by anton-staroverov** [WondrousLLC/atomic-typography#1]
To consider:
- [ ] https://github.com/necolas/normalize.css
- [ ] https://github.com/JohnAlbin/normalize-scss
- [ ] https://github.com/zurb/foundation-sites/blob/develop/scss/typography/_base.scss
- [ ] https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss

**Comment by samuells** [comment]
As we already have a working solution for css reset/normalize and this decision was made last year. I don't see any reasons, why we should change it already. I think we have more important things on our todo list as to this and this is really not needed.

Thx for your initiative.
